/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) adj_hess_toy_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#endif /* real_t */

#define to_double(x) (double) x
#define to_int(x) (int) x
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const int CASADI_PREFIX(s0)[5] = {1, 1, 0, 1, 0};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[6] = {2, 1, 0, 2, 0, 1};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[7] = {3, 1, 0, 3, 0, 1, 2};
#define s2 CASADI_PREFIX(s2)
/* adj_hess_toy */
int adj_hess_toy(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  real_t a0=arg[0] ? arg[0][0] : 0;
  real_t a1=sq(a0);
  real_t a2=(a0*a1);
  a2=(a2+a2);
  real_t a3=arg[3] ? arg[3][0] : 0;
  a2=(a2*a3);
  real_t a4=(a1*a2);
  real_t a5=(a0+a0);
  real_t a6=(a0*a2);
  real_t a7=(a5*a6);
  a4=(a4+a7);
  if (res[0]!=0) res[0][0]=a4;
  if (res[0]!=0) res[0][1]=a3;
  a4=(a0+a0);
  a7=arg[1] ? arg[1][0] : 0;
  real_t a8=(a4*a7);
  real_t a9=(a2*a8);
  real_t a10=(a1*a7);
  a8=(a0*a8);
  a10=(a10+a8);
  a10=(a10+a10);
  a10=(a3*a10);
  a8=(a1*a10);
  a9=(a9+a8);
  a8=(a7+a7);
  a8=(a6*a8);
  real_t a11=(a2*a7);
  a10=(a0*a10);
  a11=(a11+a10);
  a11=(a5*a11);
  a8=(a8+a11);
  a9=(a9+a8);
  a7=(a7*a9);
  if (res[1]!=0) res[1][0]=a7;
  a7=arg[2] ? arg[2][0] : 0;
  a9=(a7*a9);
  if (res[1]!=0) res[1][1]=a9;
  a4=(a4*a7);
  a9=(a2*a4);
  a8=(a1*a7);
  a4=(a0*a4);
  a8=(a8+a4);
  a8=(a8+a8);
  a3=(a3*a8);
  a1=(a1*a3);
  a9=(a9+a1);
  a1=(a7+a7);
  a6=(a6*a1);
  a2=(a2*a7);
  a0=(a0*a3);
  a2=(a2+a0);
  a5=(a5*a2);
  a6=(a6+a5);
  a9=(a9+a6);
  a7=(a7*a9);
  if (res[1]!=0) res[1][2]=a7;
  return 0;
}

void adj_hess_toy_incref(void) {
}

void adj_hess_toy_decref(void) {
}

int adj_hess_toy_n_in(void) { return 5;}

int adj_hess_toy_n_out(void) { return 2;}

const char* adj_hess_toy_name_in(int i){
  switch (i) {
  case 0: return "i0";
  case 1: return "i1";
  case 2: return "i2";
  case 3: return "i3";
  case 4: return "i4";
  default: return 0;
  }
}

const char* adj_hess_toy_name_out(int i){
  switch (i) {
  case 0: return "o0";
  case 1: return "o1";
  default: return 0;
  }
}

const int* adj_hess_toy_sparsity_in(int i) {
  switch (i) {
  case 0: return s0;
  case 1: return s0;
  case 2: return s0;
  case 3: return s0;
  case 4: return s0;
  default: return 0;
  }
}

const int* adj_hess_toy_sparsity_out(int i) {
  switch (i) {
  case 0: return s1;
  case 1: return s2;
  default: return 0;
  }
}

int adj_hess_toy_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 12;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
